---
title: "Histograms_Corrected_Boostrap"
author: "GGMFS Team"
date: "22/04/2021"
output: html_document
---


This script tests differences between ranges, orrecting for spatially autocorrelated error

# Load data and functions
```{r}
# Number of bootstrapped replicates
Nreps<-10 

## Libraries            
library(ggplot2)
library(nlme)

## Load Data                 
PCData<-read.csv("../PCData.csv")
MData<-PCData[,c("Region","MeanFruits","TotalDens","RosRatio","Pop_Size","Latitude","Longitude")]

# Remove missing data
MData<-MData[complete.cases(MData),]

# Can't have zero spatial distance; eliminating duplicates
# 7 observations missing because the latitudes or longitudes were the same. 
MData<-MData[!duplicated(MData[,c("Latitude","Longitude")]),]

MData
```

# Calculate Region Effect after correcting for spatial autocorrelation
```{r}
#Creating blank dataframe
X<-c(1:(Nreps+1))*NA
Coefs<-data.frame(MeanFruits=X,TotalDens=X,RosRatio=X,Pop_Size=X)

#Filling data frame with mean differences between regions  
Coefs$MeanFruits<-coef(gls(log(MeanFruits+1)~1+Region,data=MData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]

Coefs$TotalDens<-coef(gls(log(TotalDens+1)~1+Region,data=MData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]

Coefs$RosRatio<-coef(gls(RosRatio~1+Region,data=MData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]

Coefs$Pop_Size<-coef(gls(log(Pop_Size+1)~1+Region,data=MData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]

```



# Set up data for permutation test
```{r}
ptm <- proc.time()

#Creating data frame to be randomized. 
RepData<-MData


#Performing bootstraps
for(rep in 1:Nreps){
  
  #Randomizing MData
  RepData<-RepData[sample(1:nrow(RepData),nrow(RepData),replace=F),]
  
  Coefs$MeanFruits[rep+1]<-coef(gls(log(MeanFruits+1)~1+Region,data=RepData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]
  
  Coefs$TotalDens[rep+1]<-coef(gls(log(TotalDens+1)~1+Region,data=RepData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]
  
  Coefs$RosRatio[rep+1]<-coef(gls(RosRatio~1+Region,data=RepData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]
  
  Coefs$Pop_Size[rep+1]<-coef(gls(log(Pop_Size+1)~1+Region,data=RepData,correlation=corExp(form=~Longitude+Latitude|Region,nugget=T),na.action=na.exclude))[2]
  
}

proc.time() - ptm

# Calculate Means
Means<-colMeans(MData[MData$Region=="Europe",c("MeanFruits","TotalDens","RosRatio","Pop_Size")],na.rm=T)

## Translate estimated effect size to original scale of measurement
Diffs<-exp(Coefs)*Means-Means 
Diffs$RosRatio<-exp(Coefs$RosRatio) # RosRatio already a ratio



Coefs$Fruits<-coef(lm(log(MeanFruits+1)~1+Region,data=MData,na.action=na.exclude))[2]
Coefs$TotalDens<-coef(lm(log(TotalDens+1)~1+Region,data=MData,na.action=na.exclude))[2]
Coefs$RosRatio<-coef(lm(RosRatio~1+Region,data=MData,na.action=na.exclude))[2]
Coefs$Pop_Size<-coef(lm(log(Pop_Size+1)~1+Region,data=MData,na.action=na.exclude))[2]


# Exclude missing data
MData<-PCData[complete.cases(PCData[,c("Region","PCFruits","PCTotalDens","PCRosRatio","PCPopSize","Altitude","GDD","Understory","CoverPic_Mean","Pct_Canopy_Cover","MeanHerbDmg","MeanFungDmg","PctRosFung","PctAdultFung")]),]

# Can't have zero spatial distance; Removing duplicated lat long values
MData<-MData[!duplicated(MData[,c("Latitude","Longitude")]),]
```



